server:
  port: 8080

spring:
  application:
    name: DemoSimone

  datasource:
    url: jdbc:postgresql://dpg-d1jqodili9vc738lb30g-a.frankfurt-postgres.render.com:5432/develop_ywtb
    username: simo_milo
    password: 3MHVGrZgngoIIEBEgSyFhLBJf6rgv80S
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update     # o create, validate ecc., secondo le tue esigenze
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      INDENT_OUTPUT: true
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss

    deserialization:
      fail-on-unknown-properties: true
